### ISSUE TITLE
Implement navbar and placeholder pages

### ISSUE THREAD

**Issue by edoomm** [rebo-it/web#7]
## TODO

- [ ] Implement [NavBar](#NavBar)
- [ ] Implement [mobile menu](#MobileMenu)
- [ ] Create [place holder](#Placeholder) for other pages (Home, About Us, Products, Categories, Product, Order, Contact, Privacy)

## Acceptance criteria

- Navigation bar must behave as in Mock-Up
- Idea behind placeholders is to start seeing responsiveness is working fine

### NavBar
![Image](https://github.com/user-attachments/assets/669c13dd-506d-47aa-989c-2b2440abbced)

### MobileMenu
![Image](https://github.com/user-attachments/assets/16451121-0829-49f0-8a8e-6d9cf0c466d4)

### Placeholder
![Image](https://github.com/user-attachments/assets/906d6d01-5a31-494c-b567-2c6158f69457)
